name: proyecto_final_factores_flutter_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.3
  url_launcher: ^6.1.10
  intl: ^0.17.0
  flutter_polyline_points: ^1.0.0
  permission_handler: ^10.2.0
  flutter_image_compress: ^1.1.2


  # Firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  firebase_messaging: ^14.2.5

  # Get
  get: ^4.6.5
  get_storage: ^2.1.1

  # Google apis
  googleapis_auth: ^1.3.1
  image_picker: ^0.8.6+4
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  flutter_credit_card: ^3.0.6
  image_picker_web: ^3.0.0+1
 

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
    # - assets/icons/
    # - assets/images/
